assessment.url=https://ninzarin.com:8443/assessment/
eAssessTokenAPI=https://ninzarin.com:8443/assessment/generateToken
eAssessGetTestLinkApi=https://ninzarin.com:8443/assessment/getTestLinkForUser?token=$[TOKEN]&companyId=$[COMPANY_ID]&testName=$[TEST_NAME]&userId=$[EMAIL]&candidateId=$[CANDIDATE_ID]&firstName=$[FIRST_NAME]&lastName=$[LAST_NAME]
eAssessCheckTestStatusForUser=https://ninzarin.com:8443/assessment/checkIfTestUnderGoneByUser?token=$[TOKEN]&companyId=$[COMPANY_ID]&testName=$[TEST_NAME]&userId=$[EMAIL]
eAssessUserTestResultApi=https://ninzarin.com:8443/assessment/userTestSessionResult?companyId=$[COMPANY_ID]&testName=$[TEST_NAME]&email=$[EMAIL]
#fileserver.path=/opt/apps/file-server/discussions
#fileserver.url=http://localhost:91/discussions

fileserver.path=/opt/eAssess/apache-tomcat-9.0.93/webapps/ROOT/audio
fileserver.url=https://myac.ai:8443/audio/
videoServer.url=https://myac.ai:8443/videos/

ai.gemini.project.id=contactaiassessments
ai.gemini.project.location=us-central1
#ai.gemini.project.modelName=gemini-1.5-flash-001
#ai.gemini.project.modelName=gemini-2.5-pro-preview-03-25
ai.gemini.project.modelName=gemini-2.5-pro

ai.test.url=https://zimulate.me/aitest/?companyId=$[COMPANY_ID]&testIdentifier=$[TEST_IDENTIFIER]
ai.test.private.url=https://zimulate.me/aitest/privateTest?companyId=$[COMPANY_ID]&testIdentifier=$[TEST_IDENTIFIER]&firstName=$[FIRST_NAME]&lastName=$[LAST_NAME]&email=$[EMAIL]
ai.role.play.test.url=https://zimulate.me/aitest/initRolePlayTest?companyId=$[COMPANY_ID]&testName=$[TEST_NAME]
ai.role.play.test.private.url=https://zimulate.me/aitest/roleplay/privateTest?companyId=$[COMPANY_ID]&testIdentifier=$[TEST_IDENTIFIER]&firstName=$[FIRST_NAME]&lastName=$[LAST_NAME]&email=$[EMAIL]
roleplay.result.url=https://zimulate.me/roleplayresult?companyId=
elevenlabs.api.key=sk_6ebe1313cbe5abea2fdb9967eb4ec6ccbaf7fcf0238cdf85
elevenlabs.api.base.url=https://api.elevenlabs.io/v1/convai/agents
live.count.limit=2
#path.to.custom.properties=/opt/apps/ai_ass/external_properties/custom.properties
path.to.custom.properties=C:/Users/hp/Desktop/Dhruv2025/V2/zimulate_latest/src/main/resources/custom.properties  